# Generated by Django 4.1.1 on 2022-09-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apival',
            name='counter',
            field=models.PositiveSmallIntegerField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
